# BPR Hyperparameter tuning

In [15]:
from dynamicTasteDistortion.ioUtils import get_cv_results_path

from dynamicTasteDistortion.simulationConstants import input_size_to_file_name

import pandas as pd

from dynamicTasteDistortion.simulationConstants import input_size_to_file_name


import torch
dev = torch.device("cuda" if torch.cuda.is_available() else "cpu")

In [16]:
size = "s"
num_users = 1000
file_size = input_size_to_file_name[size]

In [17]:
from dynamicTasteDistortion.simulationConstants import MOVIELENS_PATH, YELP_PATH, FOOD_PATH


DATA_TO_PATH = {"ml": MOVIELENS_PATH, "yelp": YELP_PATH, "food": FOOD_PATH}

## Movielens

In [18]:
ml_results_path = get_cv_results_path(
    "ml", file_size=file_size, num_users=num_users, model_type="bpr"
)
ml_results = pd.read_csv(ml_results_path).drop(columns=["Unnamed: 0"])
ml_results

    factors       lr  reg_lambda  num_negatives  n_epochs       map
0        64  0.00010     0.00001             10        10  0.046987
1        64  0.00001     0.00010             10        10  0.045919
2        16  0.01000     0.01000              1         7  0.045562
3       128  0.00100     0.00010             10         7  0.045265
4        64  0.00010     0.01000              5         7  0.044231
5        16  0.01000     0.00100              5         7  0.043824
6       128  0.00010     0.00001             10         7  0.043413
7        32  0.01000     0.01000              5        10  0.043300
8       128  0.00010     0.01000             10        10  0.042472
9        32  0.00010     0.00001              5        10  0.041872
10       32  0.01000     0.00010              1         7  0.041475
11      128  0.00100     0.00001             10         7  0.040574
12       16  0.00100     0.00001             10        10  0.040414
13       16  0.01000     0.00100              5         5  0.040264
14       64  0.01000     0.00100             10        10  0.039466
15       32  0.00001     0.00001              5        10  0.029002
16      128  0.00001     0.00010              5         7  0.027528
17       32  0.00001     0.00100              5         5  0.026373
18      128  0.00001     0.00010              1        10  0.024454
19      128  0.00001     0.00100              1         5  0.023460

## Yelp

In [5]:
yelp_results_path = get_cv_results_path(
    "yelp", file_size=file_size, num_users=num_users, model_type="bpr"
)
yelp_results = pd.read_csv(yelp_results_path).drop(columns=["Unnamed: 0"])
yelp_results

    factors       lr  reg_lambda  num_negatives  n_epochs       map
0        32  0.00010     0.00001              5        10  0.049794
1        16  0.01000     0.01000              1         7  0.047840
2        16  0.01000     0.00100              5         7  0.046808
3       128  0.00100     0.00001             10         7  0.046670
4        32  0.01000     0.01000              5        10  0.046347
5        64  0.00001     0.00010             10        10  0.045944
6        64  0.00010     0.00001             10        10  0.045501
7        64  0.01000     0.00100             10        10  0.045057
8       128  0.00010     0.00001             10         7  0.043935
9        64  0.00010     0.01000              5         7  0.043688
10      128  0.00010     0.01000             10        10  0.043027
11       32  0.01000     0.00010              1         7  0.042398
12      128  0.00100     0.00010             10         7  0.041689
13       16  0.00100     0.00001             10        10  0.041651
14       16  0.01000     0.00100              5         5  0.041596
15      128  0.00001     0.00010              1        10  0.041404
16       32  0.00001     0.00001              5        10  0.041063
17      128  0.00001     0.00010              5         7  0.040093
18      128  0.00001     0.00100              1         5  0.039233
19       32  0.00001     0.00100              5         5  0.038455

# Oracle model

## [ML] Oracle model

In [6]:
path = "dynamicTasteDistortion/artifacts/results/ml_1m/oracle_model_f1_results.pkl"

In [7]:
results = pd.read_pickle(path)

In [8]:
results

,model_name,params,validation_f1,test_f1,is_winning_variant
0,SVD,"{'n_factors': 15, 'n_epochs': 30, 'lr_all': 0....",0.505645,NaN,False
1,SVD,"{'n_factors': 30, 'n_epochs': 30, 'lr_all': 0....",0.510479,NaN,False
2,SVD,"{'n_factors': 15, 'n_epochs': 10, 'lr_all': 0....",0.477281,NaN,False
3,SVD,"{'n_factors': 100, 'n_epochs': 30, 'lr_all': 0...",0.503008,NaN,False
4,SVD,"{'n_factors': 30, 'n_epochs': 10, 'lr_all': 0....",0.500629,NaN,False
...,...,...,...,...,...
80,NMF,"{'n_factors': 30, 'n_epochs': 100, 'reg_pu': 0...",0.560511,NaN,False
81,NMF,"{'n_factors': 100, 'n_epochs': 100, 'reg_pu': ...",0.647412,NaN,False
82,NMF,"{'n_factors': 100, 'n_epochs': 50, 'reg_pu': 0...",0.721591,NaN,False
83,NMF,"{'n_factors': 100, 'n_epochs': 100, 'reg_pu': ...",0.753906,NaN,False
84,NMF,"{'n_factors': 100, 'n_epochs': 50, 'reg_pu': 0...",0.757246,0.747022,True

In [9]:
winners = results[results["is_winning_variant"] == True]

In [10]:
pd.set_option('display.max_colwidth', None)

In [11]:
winners

,model_name,params,validation_f1,test_f1,is_winning_variant
16,SVD,"{'n_factors': 30, 'n_epochs': 30, 'lr_all': 0.01, 'reg_all': 0.02}",0.575029,0.560252,True
45,SVD++,"{'n_factors': 30, 'n_epochs': 30, 'lr_all': 0.01, 'reg_all': 0.02}",0.573192,0.562719,True
84,NMF,"{'n_factors': 100, 'n_epochs': 50, 'reg_pu': 0.05, 'reg_qi': 0.05}",0.757246,0.747022,True

## Yelp 1m

In [12]:
yelp = pd.read_pickle("dynamicTasteDistortion/artifacts/results/yelp_1m/oracle_model_f1_results.pkl")

In [13]:
yelp

,model_name,params,validation_f1,test_f1,is_winning_variant
0,SVD,"{'n_factors': 15, 'n_epochs': 30, 'lr_all': 0.002, 'reg_all': 0.05}",0.651385,NaN,False
1,SVD,"{'n_factors': 30, 'n_epochs': 30, 'lr_all': 0.01, 'reg_all': 0.1}",0.676120,0.683712,True
2,SVD,"{'n_factors': 15, 'n_epochs': 10, 'lr_all': 0.002, 'reg_all': 0.1}",0.579866,NaN,False
3,SVD,"{'n_factors': 100, 'n_epochs': 30, 'lr_all': 0.005, 'reg_all': 0.1}",0.666993,NaN,False
4,SVD,"{'n_factors': 30, 'n_epochs': 10, 'lr_all': 0.005, 'reg_all': 0.05}",0.643885,NaN,False
...,...,...,...,...,...
80,NMF,"{'n_factors': 30, 'n_epochs': 100, 'reg_pu': 0.05, 'reg_qi': 0.05}",0.539459,NaN,False
81,NMF,"{'n_factors': 100, 'n_epochs': 100, 'reg_pu': 0.02, 'reg_qi': 0.1}",0.633116,NaN,False
82,NMF,"{'n_factors': 100, 'n_epochs': 50, 'reg_pu': 0.02, 'reg_qi': 0.05}",0.817009,0.816323,True
83,NMF,"{'n_factors': 100, 'n_epochs': 100, 'reg_pu': 0.02, 'reg_qi': 0.02}",0.801510,NaN,False
84,NMF,"{'n_factors': 100, 'n_epochs': 50, 'reg_pu': 0.05, 'reg_qi': 0.05}",0.793131,NaN,False

In [14]:
yelp[yelp["is_winning_variant"]]

,model_name,params,validation_f1,test_f1,is_winning_variant
1,SVD,"{'n_factors': 30, 'n_epochs': 30, 'lr_all': 0.01, 'reg_all': 0.1}",0.676120,0.683712,True
30,SVD++,"{'n_factors': 30, 'n_epochs': 30, 'lr_all': 0.01, 'reg_all': 0.1}",0.673943,0.679041,True
82,NMF,"{'n_factors': 100, 'n_epochs': 50, 'reg_pu': 0.02, 'reg_qi': 0.05}",0.817009,0.816323,True