In [1]:
import pandas as pd

## [ML] Oracle model

In [2]:
path = "dynamicTasteDistortion/artifacts/results/ml_1m/oracle_model_f1_results.pkl"

In [4]:
results = pd.read_pickle(path)

In [5]:
results

,model_name,params,validation_f1,test_f1,is_winning_variant
0,SVD,"{'n_factors': 15, 'n_epochs': 30, 'lr_all': 0....",0.503372,NaN,False
1,SVD,"{'n_factors': 30, 'n_epochs': 30, 'lr_all': 0....",0.522193,NaN,False
2,SVD,"{'n_factors': 15, 'n_epochs': 10, 'lr_all': 0....",0.449675,NaN,False
3,SVD,"{'n_factors': 100, 'n_epochs': 30, 'lr_all': 0...",0.508695,NaN,False
4,SVD,"{'n_factors': 30, 'n_epochs': 10, 'lr_all': 0....",0.495730,NaN,False
...,...,...,...,...,...
80,NMF,"{'n_factors': 30, 'n_epochs': 100, 'reg_pu': 0...",0.546809,NaN,False
81,NMF,"{'n_factors': 100, 'n_epochs': 100, 'reg_pu': ...",0.605904,NaN,False
82,NMF,"{'n_factors': 100, 'n_epochs': 50, 'reg_pu': 0...",0.722960,NaN,False
83,NMF,"{'n_factors': 100, 'n_epochs': 100, 'reg_pu': ...",0.746299,NaN,False
84,NMF,"{'n_factors': 100, 'n_epochs': 50, 'reg_pu': 0...",0.751800,0.744881,True

In [6]:
winners = results[results["is_winning_variant"] == True]

In [7]:
winners

,model_name,params,validation_f1,test_f1,is_winning_variant
16,SVD,"{'n_factors': 30, 'n_epochs': 30, 'lr_all': 0....",0.559714,0.538013,True
45,SVD++,"{'n_factors': 30, 'n_epochs': 30, 'lr_all': 0....",0.556578,0.536050,True
84,NMF,"{'n_factors': 100, 'n_epochs': 50, 'reg_pu': 0...",0.751800,0.744881,True

In [8]:
results[results["model_name"] != "NMF"]

,model_name,params,validation_f1,test_f1,is_winning_variant
0,SVD,"{'n_factors': 15, 'n_epochs': 30, 'lr_all': 0....",0.503372,NaN,False
1,SVD,"{'n_factors': 30, 'n_epochs': 30, 'lr_all': 0....",0.522193,NaN,False
2,SVD,"{'n_factors': 15, 'n_epochs': 10, 'lr_all': 0....",0.449675,NaN,False
3,SVD,"{'n_factors': 100, 'n_epochs': 30, 'lr_all': 0...",0.508695,NaN,False
4,SVD,"{'n_factors': 30, 'n_epochs': 10, 'lr_all': 0....",0.495730,NaN,False
5,SVD,"{'n_factors': 30, 'n_epochs': 20, 'lr_all': 0....",0.510326,NaN,False
6,SVD,"{'n_factors': 100, 'n_epochs': 20, 'lr_all': 0...",0.481554,NaN,False
7,SVD,"{'n_factors': 30, 'n_epochs': 20, 'lr_all': 0....",0.496994,NaN,False
8,SVD,"{'n_factors': 15, 'n_epochs': 20, 'lr_all': 0....",0.521878,NaN,False
9,SVD,"{'n_factors': 100, 'n_epochs': 30, 'lr_all': 0...",0.539031,NaN,False
10,SVD,"{'n_factors': 15, 'n_epochs': 30, 'lr_all': 0....",0.527380,NaN,False
11,SVD,"{'n_factors': 15, 'n_epochs': 30, 'lr_all': 0....",0.490320,NaN,False
12,SVD,"{'n_factors': 100, 'n_epochs': 30, 'lr_all': 0...",0.534916,NaN,False
13,SVD,"{'n_factors': 30, 'n_epochs': 10, 'lr_all': 0....",0.484792,NaN,False
14,SVD,"{'n_factors': 100, 'n_epochs': 30, 'lr_all': 0...",0.491071,NaN,False
15,SVD,"{'n_factors': 100, 'n_epochs': 20, 'lr_all': 0...",0.515063,NaN,False
16,SVD,"{'n_factors': 30, 'n_epochs': 30, 'lr_all': 0....",0.559714,0.538013,True
17,SVD,"{'n_factors': 100, 'n_epochs': 20, 'lr_all': 0...",0.522422,NaN,False
18,SVD,"{'n_factors': 15, 'n_epochs': 30, 'lr_all': 0....",0.507342,NaN,False
19,SVD,"{'n_factors': 100, 'n_epochs': 10, 'lr_all': 0...",0.504682,NaN,False
20,SVD,"{'n_factors': 100, 'n_epochs': 30, 'lr_all': 0...",0.529146,NaN,False
21,SVD,"{'n_factors': 30, 'n_epochs': 20, 'lr_all': 0....",0.491545,NaN,False
22,SVD,"{'n_factors': 15, 'n_epochs': 10, 'lr_all': 0....",0.524320,NaN,False
23,SVD,"{'n_factors': 30, 'n_epochs': 30, 'lr_all': 0....",0.505315,NaN,False
24,SVD,"{'n_factors': 30, 'n_epochs': 10, 'lr_all': 0....",0.458458,NaN,False
25,SVD,"{'n_factors': 100, 'n_epochs': 10, 'lr_all': 0...",0.514527,NaN,False
26,SVD,"{'n_factors': 100, 'n_epochs': 30, 'lr_all': 0...",0.545939,NaN,False
27,SVD,"{'n_factors': 100, 'n_epochs': 10, 'lr_all': 0...",0.457495,NaN,False
28,SVD,"{'n_factors': 15, 'n_epochs': 20, 'lr_all': 0....",0.482159,NaN,False
29,SVD++,"{'n_factors': 15, 'n_epochs': 30, 'lr_all': 0....",0.502712,NaN,False
30,SVD++,"{'n_factors': 30, 'n_epochs': 30, 'lr_all': 0....",0.526595,NaN,False
31,SVD++,"{'n_factors': 15, 'n_epochs': 10, 'lr_all': 0....",0.449153,NaN,False
32,SVD++,"{'n_factors': 100, 'n_epochs': 30, 'lr_all': 0...",0.512291,NaN,False
33,SVD++,"{'n_factors': 30, 'n_epochs': 10, 'lr_all': 0....",0.501425,NaN,False
34,SVD++,"{'n_factors': 30, 'n_epochs': 20, 'lr_all': 0....",0.518033,NaN,False
35,SVD++,"{'n_factors': 100, 'n_epochs': 20, 'lr_all': 0...",0.483183,NaN,False
36,SVD++,"{'n_factors': 30, 'n_epochs': 20, 'lr_all': 0....",0.505210,NaN,False
37,SVD++,"{'n_factors': 15, 'n_epochs': 20, 'lr_all': 0....",0.529832,NaN,False
38,SVD++,"{'n_factors': 100, 'n_epochs': 30, 'lr_all': 0...",0.543349,NaN,False
39,SVD++,"{'n_factors': 15, 'n_epochs': 30, 'lr_all': 0....",0.526499,NaN,False
40,SVD++,"{'n_factors': 15, 'n_epochs': 30, 'lr_all': 0....",0.491773,NaN,False
41,SVD++,"{'n_factors': 100, 'n_epochs': 30, 'lr_all': 0...",0.539048,NaN,False
42,SVD++,"{'n_factors': 30, 'n_epochs': 10, 'lr_all': 0....",0.483928,NaN,False
43,SVD++,"{'n_factors': 100, 'n_epochs': 30, 'lr_all': 0...",0.493445,NaN,False
44,SVD++,"{'n_factors': 100, 'n_epochs': 20, 'lr_all': 0...",0.518485,NaN,False
45,SVD++,"{'n_factors': 30, 'n_epochs': 30, 'lr_all': 0....",0.556578,0.536050,True
46,SVD++,"{'n_factors': 100, 'n_epochs': 20, 'lr_all': 0...",0.530518,NaN,False
47,SVD++,"{'n_factors': 15, 'n_epochs': 30, 'lr_all': 0....",0.515648,NaN,False
48,SVD++,"{'n_factors': 100, 'n_epochs': 10, 'lr_all': 0...",0.517766,NaN,False
49,SVD++,"{'n_factors': 100, 'n_epochs': 30, 'lr_all': 0...",0.534941,NaN,False
50,SVD++,"{'n_factors': 30, 'n_epochs': 20, 'lr_all': 0....",0.492141,NaN,False
51,SVD++,"{'n_factors': 15, 'n_epochs': 10, 'lr_all': 0....",0.531955,NaN,False
52,SVD++,"{'n_factors': 30, 'n_epochs': 30, 'lr_all': 0....",0.504980,NaN,False
53,SVD++,"{'n_factors': 30, 'n_epochs': 10, 'lr_all': 0....",0.461247,NaN,False
54,SVD++,"{'n_factors': 100, 'n_epochs': 10, 'lr_all': 0...",0.520397,NaN,False
55,SVD++,"{'n_factors': 100, 'n_epochs': 30, 'lr_all': 0...",0.548247,NaN,False
56,SVD++,"{'n_factors': 100, 'n_epochs': 10, 'lr_all': 0...",0.462814,NaN,False
57,SVD++,"{'n_factors': 15, 'n_epochs': 20, 'lr_all': 0....",0.480182,NaN,False